version: '3.8'

services:
  app:
    image: minha-imagem-segura
    networks:
      secure_internal_network:
        aliases:
          - secure-app

networks:
  secure_internal_network:
    external: true